# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Structures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('lecture_name', models.CharField(max_length=150)),
                ('lecture_contents', models.CharField(max_length=200)),
                ('teaching_method', models.CharField(max_length=200)),
                ('assessment_method', models.CharField(max_length=200)),
            ],
        ),
    ]
