# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question_text', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('question_type', models.CharField(max_length=100)),
                ('question_category', models.CharField(max_length=100)),
                ('specialist_department', models.CharField(max_length=200)),
            ],
        ),
    ]
