# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='secondname',
            new_name='second_name',
        ),
    ]
